replicaCount: 1

image:
  repository: invoice-extractor
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: S3_ENDPOINT_URL
    value: "http://minio:9000"
  - name: S3_DEFAULT_REGION
    value: "us-east-1"
  - name: S3_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: accesskey
  - name: S3_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: secretkey
  - name: POLL_INTERVAL
    value: "5"

# OpenTelemetry configuration
otel:
  enabled: true
  endpoint: "otel-collector:4317"

# Minio configuration
minio:
  accessKey: "minioadmin"
  secretKey: "minioadmin"